#!/usr/bin/perl -w

# shadow: Perl IRC Bot
#
# Written by Aaron Blakely

use lib './lib';
use strict;
use warnings;
use Shadow::Core;
use Shadow::Config;

$| = 1;

if ($ARGV[0] eq "-h" || $ARGV[0] eq "--help") {
	print "Usage: ./shadow [config file]\n\n";
	print "shadow is a modular perl IRC bot written by Aaron Blakely <aaron\@ephasic.org>\n";
	print "github: http://github.com/ablakely/shadow\n";

	exit;
}

my $configfile		= $ARGV[0] || './etc/shadow.conf';



my $bot = Shadow::Core->new($configfile, 1);

foreach my $mod (@{$Shadow::Core::options{cfg}->{Shadow}->{Bot}->{system}->{modules}}) {
  $bot->load_module($mod);
}

# Start the wheel...
$bot->connect();
