#!/usr/bin/perl -w

# shadow: Perl IRC Bot
#
# Written by Aaron Blakely <aaron@ephasic.org>
#

use lib './lib';
use lib '.';
use strict;
use warnings;
use Shadow::Core;
use Shadow::Config;

$|                = 1;
my $verbose       = 0;
my $nofork        = 0;
my $idx           = 0;

my $configfile    = './etc/shadow.conf';
my @cmdloadmods;

MODS:
if ($ARGV[$idx] eq "-v" || $ARGV[$idx] eq "--verbose") {
	$verbose = 1;
	print "[INFO] Setting verbose.\n";
	$idx++;
}

if ($ARGV[$idx] eq "-c" || $ARGV[$idx] eq "--conf") {
	$configfile = $ARGV[++$idx];
	print "[INFO] Using config file: $configfile\n";

	$idx++;
	goto MODS;
}

if ($ARGV[$idx] eq "-m" || $ARGV[$idx] eq "--module") {
	my $cmod = $ARGV[++$idx];
	push(@cmdloadmods, $cmod);
	print "[INFO] Command line module load: $cmod\n";

	$idx++;
	goto MODS;
}

if ($ARGV[$idx] eq "-n" || $ARGV[$idx] eq "--nofork") {
	$nofork = 1;
	print "[INFO] Not forking to background.\n";
	
	$idx++;
	goto MODS;
}

if ($ARGV[$idx] eq "-V" || $ARGV[$idx] eq "--version") {
	print "\n".$Shadow::Core::options{config}->{version}."\n\nCopyright (c) 2012-2019 Aaron Blakely\n";
	
	exit;
}

if ($ARGV[$idx] eq "-h" || $ARGV[0] eq "--help") {
	print "$0: [-c config] [-m module] [-vhnV]\n";
	print "\nShadow Help:\n\n";
	print "[Usage]\n";
	print " -v          - Enables verbose\n";
	print " -h          - Displays this message\n";
	print " -V          - Display version info\n";
	print " -n          - Disables forking to the background\n";
	print " -c [config] - Set the config file path (default: $configfile)\n";
	print " -m [module] - Load module\n\n";
	print "github: http://github.com/ablakely/shadow\n";

	exit;
}

my $bot = Shadow::Core->new($configfile, $verbose, $nofork);

foreach my $mod (@{$Shadow::Core::options{cfg}->{Shadow}->{Bot}->{system}->{modules}}) {
  $bot->load_module($mod);
}

foreach my $mod (@cmdloadmods) {
	$bot->load_module($mod);
}


# Start the wheel...
$bot->connect();
